include colors_256.conf
#window
hide_window_decorations yes
#fonts
font_family      family='MartianMono Nerd Font' postscript_name=MartianMonoNF-Bold
bold_font        family='MartianMono Nerd Font' postscript_name=MartianMonoNF-Bold
italic_font      auto
bold_italic_font auto
font_size 9
#colors
foreground #000000
background #D6D3D1
#cursor
cursor #000000
cursor_text_color #FFFFFF
#colors color
color1 #000000
color2 #AA7070
color3 #AA20AA
color4 #7070AA
color5 #7070AA
color6 #AA9090
color7 #AA7070
color8 #000000
color9 #000000
color10 #AA7070
color11 #AA20AA
color12 #7070AA
color13 #7070AA
color14 #AA9090
color15 #AA7070
color185 #AA20AA
#color16 #808080
#color255 #808080
#url color
url_color #000000
#color for marks
#foreground
mark1_foreground black
mark2_foreground black
mark3_foreground black
#background
#mark1_background black
#mark2_background black
#mark3_background black
#https://manpages.debian.org/unstable/kitty/kitty.conf.5.en.html
#print colors
#for i in {0..255}; do printf "\x1b[38;5;${i}mcolor%-4d\x1b[0m " "$i"; if [ $(( ($i + 1) % 8 )) -eq 0 ]; then echo; fi; done
#for i in {16..255}; do echo "color$i #808080" >> ~/.config/kitty/colors_256.conf; done
#for i in {16..255}; do echo "color$i #505050" >> ~/.config/kitty/colors_256.conf; done
#for i in {16..255}; do echo "color$i #AA500A" >> ~/.config/kitty/colors_256.conf; done
#tcursor_text_color #000000
#border
#window_border_width 0.5pt
#draw_window_borders_for_single_window yes
#draw_minimal_borders yes
#active_border_color #000000


