#window
hide_window_decorations yes
#fonts
font_family      family='Monaspace Argon NF' postscript_name=MonaspaceArgonNF-ExtraBold
bold_font        family='Monaspace Argon NF' postscript_name=MonaspaceArgonNF-ExtraBold
italic_font      auto
bold_italic_font auto
#font_size 8
#colors
foreground #000000
background #D6D3D1
cursor #000000
#tcursor_text_color #000000
#border
#window_border_width 0.5pt
#draw_window_borders_for_single_window yes
#draw_minimal_borders yes
#active_border_color #000000


